### ISSUE TITLE
Readme's explanation about Convert file to mdb is not correct

### ISSUE THREAD

**Issue by HinataKikuchi** [di-dimitrov/propaganda-techniques-in-memes#2]
Maybe the step iii. d.  from [Preparation for running steps](https://github.com/di-dimitrov/propaganda-techniques-in-memes#follow-these-steps-to-get-all-the-code-ready-and-running) is not correct

❌
> After feature extraction is done convert the features to a .mdb file with the following script: ```mmf/tools/scripts/features/extract_features_vmb.py```

⭕
> After feature extraction is done convert the features to a .mdb file with the following script: 
```mmf/tools/scripts/features/lmdb_conversion.py```

**Comment by di-dimitrov** [comment]
That is absolutely correct! This is a mistake on our side, will fix it immediately. 

Thank you for the feedback 👍

**Comment by di-dimitrov** [comment]
Fixed with commit 45d3e7737c26bd72b0b3560afff4d80df7784ddd.
